### ISSUE TITLE
Create user story

### ISSUE THREAD

**Issue by NileshPatel83** [NileshPatel83/Trivia-Games#1]

**Comment by TheIPM** [comment]
AS A Person with a few minutes to spare 
I WANT to entertain myself with random trivia, and be able to search wikipedia to learn about the questions
SO THAT I can test my knowledge and have fun


When I go on the web page I am given a list to choose a trivia topic
Then I can play the game
When I encounter a question i dont understand
Then I can search for the topic on wikipedia to find the answer

**Comment by NileshPatel83** [comment]
Complete.
